config/routes.rb
Rails.application.routes.draw do
	root 'scholars#index'
  resources :scholars

end

app/models/scholar.rb
class Scholar < ActiveRecord::Base
	has_one :title
end

app/models/title.rb
class Title < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scholars_controller.rb
class ScholarsController < ApplicationController
  before_action :set_scholar, only: [:show, :edit, :update, :destroy]

  # GET /scholars
  # GET /scholars.json
  def index
    @scholars = Scholar.all
  end

  # GET /scholars/1
  # GET /scholars/1.json
  def show
  end

  # GET /scholars/new
  def new
    @scholar = Scholar.new
  end

  # GET /scholars/1/edit
  def edit
  end

  # POST /scholars
  # POST /scholars.json
  def create
    @scholar = Scholar.new(scholar_params)

    respond_to do |format|
      if @scholar.save
        format.html { redirect_to @scholar, notice: 'Scholar was successfully created.' }
        format.json { render :show, status: :created, location: @scholar }
      else
        format.html { render :new }
        format.json { render json: @scholar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholars/1
  # PATCH/PUT /scholars/1.json
  def update
    respond_to do |format|
      if @scholar.update(scholar_params)
        format.html { redirect_to @scholar, notice: 'Scholar was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholar }
      else
        format.html { render :edit }
        format.json { render json: @scholar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholars/1
  # DELETE /scholars/1.json
  def destroy
    @scholar.destroy
    respond_to do |format|
      format.html { redirect_to scholars_url, notice: 'Scholar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholar
      @scholar = Scholar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholar_params
      params.require(:scholar).permit(:firstname, :lastname, :department)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scholars_helper.rb
module ScholarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crmotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scholars/_form.html.erb
<%= form_for(@scholar) do |f| %>
  <% if @scholar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scholar.errors.count, "error") %> prohibited this scholar from being saved:</h2>

      <ul>
      <% @scholar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.collection_select :title, Title.all, :id, :title_id, prompt: false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scholars/edit.html.erb
<h1>Editing Scholar</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholar %> |
<%= link_to 'Back', scholars_path %>

app/views/scholars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scholars</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholars.each do |scholar| %>
      <tr>
        <td><%= scholar.firstname %></td>
        <td><%= scholar.lastname %></td>
        <td><%= scholar.department %></td>

        <td><%= link_to 'Show', scholar %></td>
        <td><%= link_to 'Edit', edit_scholar_path(scholar) %></td>
        <td><%= link_to 'Destroy', scholar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scholar', new_scholar_path %>

app/views/scholars/new.html.erb
<h1>New Scholar</h1>

<%= render 'form' %>

<%= link_to 'Back', scholars_path %>

app/views/scholars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @scholar.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @scholar.lastname %>
</p>

<p>
  <strong>Department:</strong>
  <%= @scholar.department %>
</p>

<%= link_to 'Edit', edit_scholar_path(@scholar) %> |
<%= link_to 'Back', scholars_path %>